### ISSUE TITLE
Needs update for new GitHub UI

### ISSUE THREAD

**Issue by Richienb** [sqren/github-widescreen#12]
The new GitHub UI currently in feature preview is not supported by this extension.

This is the CSS required for it to work:

```css
.container-xl.clearfix.new-discussion-timeline.px-3.px-md-4.px-lg-5 {
    max-width: 100%;
}
```

cc @sqren
